/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author koushalamshala
 */
public class AddEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployeeJPanel
     */
    public AddEmployeeJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AddEmpLbl = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        AgeLbl = new javax.swing.JLabel();
        Agetxt = new javax.swing.JTextField();
        GenderLbl = new javax.swing.JLabel();
        JobLbl = new javax.swing.JLabel();
        SalaryLbl = new javax.swing.JLabel();
        Salarytxt = new javax.swing.JTextField();
        AddressLbl = new javax.swing.JLabel();
        Addresstxt = new javax.swing.JTextField();
        UserNameLbl = new javax.swing.JLabel();
        PasswordLbl = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JTextField();
        UserNametxt = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        MaleBtn = new javax.swing.JRadioButton();
        FemaleBtn = new javax.swing.JRadioButton();
        OthersBtn = new javax.swing.JRadioButton();
        JobCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddEmpLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        AddEmpLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddEmpLbl.setText("Add Employee");
        add(AddEmpLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 580, 26));

        NameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        NameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLbl.setText("Name");
        add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 65, 27));

        Nametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 174, -1));

        AgeLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        AgeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgeLbl.setText("Age");
        add(AgeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 65, 23));

        Agetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 174, -1));

        GenderLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        GenderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenderLbl.setText("Gender");
        add(GenderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 65, 25));

        JobLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        JobLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobLbl.setText("Job");
        add(JobLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 65, 27));

        SalaryLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SalaryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalaryLbl.setText("Salary");
        add(SalaryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 65, 26));

        Salarytxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 174, 26));

        AddressLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        AddressLbl.setText("Address");
        add(AddressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 65, 25));

        Addresstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddresstxtActionPerformed(evt);
            }
        });
        add(Addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 174, 24));

        UserNameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        UserNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNameLbl.setText("User Name");
        add(UserNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, 26));

        PasswordLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        PasswordLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLbl.setText("Password");
        add(PasswordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 65, 25));

        Passwordtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 174, 26));

        UserNametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(UserNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 174, 26));

        SubmitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SubmitBtn.setText("Submit");
        add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        buttonGroup1.add(MaleBtn);
        MaleBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        MaleBtn.setText("Male");
        add(MaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 54, -1));

        buttonGroup1.add(FemaleBtn);
        FemaleBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        FemaleBtn.setText("Female");
        add(FemaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        buttonGroup1.add(OthersBtn);
        OthersBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        OthersBtn.setText("Others");
        add(OthersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        JobCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "Receptionist", "HouseKeeping", "Driver", "Chef" }));
        JobCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobComboboxActionPerformed(evt);
            }
        });
        add(JobCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 174, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add employee.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AddresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddresstxtActionPerformed

    private void JobComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JobComboboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddEmpLbl;
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JTextField Addresstxt;
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField Agetxt;
    private javax.swing.JRadioButton FemaleBtn;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JComboBox<String> JobCombobox;
    private javax.swing.JLabel JobLbl;
    private javax.swing.JRadioButton MaleBtn;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JRadioButton OthersBtn;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JTextField Passwordtxt;
    private javax.swing.JLabel SalaryLbl;
    private javax.swing.JTextField Salarytxt;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JTextField UserNametxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
