/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author sahithi
 */
public class AddEmpJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddEmpJFrame
     */
    public AddEmpJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEmpLbl = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        AgeLbl = new javax.swing.JLabel();
        Agetxt = new javax.swing.JTextField();
        GenderLbl = new javax.swing.JLabel();
        MaleBtn = new javax.swing.JRadioButton();
        FemaleBtn = new javax.swing.JRadioButton();
        OthersBtn = new javax.swing.JRadioButton();
        JobCombobox = new javax.swing.JComboBox<>();
        JobLbl = new javax.swing.JLabel();
        SalaryLbl = new javax.swing.JLabel();
        Salarytxt = new javax.swing.JTextField();
        AddressLbl = new javax.swing.JLabel();
        Addresstxt = new javax.swing.JTextField();
        UserNameLbl = new javax.swing.JLabel();
        UserNametxt = new javax.swing.JTextField();
        Passwordtxt = new javax.swing.JTextField();
        PasswordLbl = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddEmpLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        AddEmpLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddEmpLbl.setText("Add Employee");

        NameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        NameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLbl.setText("Name");

        Nametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AgeLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        AgeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgeLbl.setText("Age");

        Agetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        GenderLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        GenderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenderLbl.setText("Gender");

        MaleBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        MaleBtn.setText("Male");

        FemaleBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        FemaleBtn.setText("Female");

        OthersBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        OthersBtn.setText("Others");

        JobCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "Receptionist", "HouseKeeping", "Driver", "Chef" }));
        JobCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobComboboxActionPerformed(evt);
            }
        });

        JobLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        JobLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobLbl.setText("Job");

        SalaryLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SalaryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalaryLbl.setText("Salary");

        Salarytxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AddressLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        AddressLbl.setText("Address");

        Addresstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddresstxtActionPerformed(evt);
            }
        });

        UserNameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        UserNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNameLbl.setText("User Name");

        UserNametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Passwordtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        PasswordLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        PasswordLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLbl.setText("Password");

        SubmitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SubmitBtn.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(NameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FemaleBtn)
                                .addGap(18, 18, 18)
                                .addComponent(OthersBtn))
                            .addComponent(Agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(482, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AddEmpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(JobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(JobCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(SalaryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(Salarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(AddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(Addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(UserNameLbl)
                            .addGap(51, 51, 51)
                            .addComponent(UserNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(PasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(Passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(SubmitBtn)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GenderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaleBtn)
                        .addComponent(FemaleBtn)
                        .addComponent(OthersBtn)))
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddEmpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(164, 164, 164)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JobCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SalaryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Salarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UserNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addComponent(SubmitBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JobComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JobComboboxActionPerformed

    private void AddresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddresstxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmpJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddEmpLbl;
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JTextField Addresstxt;
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField Agetxt;
    private javax.swing.JRadioButton FemaleBtn;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JComboBox<String> JobCombobox;
    private javax.swing.JLabel JobLbl;
    private javax.swing.JRadioButton MaleBtn;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JRadioButton OthersBtn;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JTextField Passwordtxt;
    private javax.swing.JLabel SalaryLbl;
    private javax.swing.JTextField Salarytxt;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JTextField UserNametxt;
    // End of variables declaration//GEN-END:variables
}
