 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import database.ConnectionProvider;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.CheckIn;
import net.proteanit.sql.DbUtils;
//import net.proteanit.sql.DbUtils;

/**
 *
 * @author sahithi
 */
public class CheckOutJFrame extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    
    
    /**
    /**
     * Creates new form CheckOutJFrame
     */
    public CheckOutJFrame() {
        initComponents();
        con = ConnectionProvider.getCon();
        populateTable();
        
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        
        /*SimpleDateFormat myFormat = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal = Calendar.getInstance();
        jTextField4.setText(myFormat.format(cal.getTime()));*/
    }
    
    int id=0;
    String Query;
    String roomType;
    String bedType;
    String roomno;
    
    public void populateTable()
    {
        try{
            String sql = "SELECT id,name,mobileno,nationality,gender,email,idproof,address,checkin,roomno,bedType,roomType,price FROM checkin WHERE checkout is NULL";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        checkoutButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(50, 118));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel2.setText("Room No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 59, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 52, 134, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Customer Name", "Mobile No", "Nationality", "Gender", "Email", "ID Proof", "Address", "CheckIn Date", "Room No", "Bed Type", "Room Type", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1300, 212));

        jLabel3.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel3.setText("Customer Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 122, -1, -1));

        jTextField2.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 150, 188, -1));

        jLabel4.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel4.setText("Check In Date :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, -1));

        jTextField3.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 170, -1));

        jLabel5.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel5.setText("Check Out Date :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jTextField4.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 30));

        jLabel6.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel6.setText("Customer Mobile No :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jTextField5.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 181, -1));

        jLabel7.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel7.setText("Price Per Day :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 140, 30));

        jLabel8.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel8.setText("No of Days Stayed :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 190, 30));

        jLabel9.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel9.setText("Total Amount to be Collected from Customer :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 400, -1));

        jTextField6.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 210, 30));

        jTextField7.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 260, 30));

        jTextField8.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 370, 30));

        jLabel10.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        jLabel10.setText("Email Id : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        jTextField9.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 250, -1));

        checkoutButton.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        checkoutButton.setText("Check Out");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 120, 40));

        ClearButton.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 120, 40));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, -1, -1));

        BackButton.setBackground(new java.awt.Color(204, 204, 204));
        BackButton.setFont(new java.awt.Font("Big Caslon", 1, 18)); // NOI18N
        BackButton.setText("Log Out");
        BackButton.setBorder(null);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CheckOutJFrame().setVisible(true);
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
        String name = jTextField2.getText();
        String mobileno = jTextField5.getText();
        String email  = jTextField9.getText();
        String checkout = jTextField4.getText();
        String daysstayed = jTextField7.getText();
        String totalamt = jTextField8.getText();
        roomno = jTextField1.getText();
        
        Connection con = ConnectionProvider.getCon();
        CheckIn c = new CheckIn();
        c.setId(id);
        c.setName(name);
        c.setMobileno(mobileno);
        //c.setGender(gender);
        c.setEmail(email);
        //c.setIdproof(idproof);
        //c.setAddress(address);
        //c.setCheckin(checkIn);
        c.setRoomno(roomno);
        c.setBedType(bedType);
        c.setRoomType(roomType);
        //c.setPrice(price);
        c.setDaysstayed(daysstayed);
        c.setTotalamt(totalamt);
        c.setCheckout(checkout);
        Query = "UPDATE checkin SET daysstayed=? AND totalamt=? AND checkout =? WHERE id='"+id+"'";
        try {
            ps=con.prepareStatement(Query);
            ps.setString(1, daysstayed);
            ps.setString(2,totalamt);
            ps.setString(3,checkout);
            //ps.setString(4,id);
            ps.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        Query = "UPDATE rooms SET status='Not Booked' WHERE roomno='"+roomno+"'";
        try{
            ps=con.prepareStatement(Query);
            ps.execute();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        String path="";    
        JFileChooser j =new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x= j.showSaveDialog(this);
        if(x==JFileChooser.APPROVE_OPTION){
            path=j.getSelectedFile().getPath();
        }
        
        Document doc = new Document();
        //com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try{
            int r=jTable1.getSelectedRow();
            String click = (jTable1.getModel().getValueAt(r, 0).toString());
            String sql = "SELECT * FROM checkin WHERE id='"+click+"'";
            try{
                ps=con.prepareCall(sql);
                rs=ps.executeQuery();
                if(rs.next()){
                    String id = rs.getString(1);
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            PdfWriter.getInstance(doc, new FileOutputStream("path"+id+".pdf"));
            doc.open();
            Paragraph paragraph1 =  new Paragraph("                                             Palm Tree Resorts                                   ");
            doc.add(paragraph1);
            Paragraph paragraph2 =  new Paragraph("*************************************************************************************************");
            doc.add(paragraph2);
            Paragraph paragraph3 =  new Paragraph("\tBill ID : "+id+"\nCustomer Details:\nCustomer Name: "+name+"\nMobile Number: "+mobileno+"\nEmail: "+email+"\n");
            doc.add(paragraph3);
            Paragraph paragraph4 =  new Paragraph("\tRoom Details: \nRoom No: "+jTextField1.getText()+"\nRoom Type: "+roomType+"\nBed Type: "+bedType+"\n Price per day: "+jTextField6.getText()+"\n");
            doc.add(paragraph4);
            doc.add(paragraph2);
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell("Check In Date: "+jTextField3.getText());
            tbl.addCell("Check Out Date: "+checkout);
            tbl.addCell("No of days Stayed: "+daysstayed);
            tbl.addCell("Total Amount Paid: "+jTextField8.getText());
            doc.add(tbl);
            doc.add(paragraph2);
            Paragraph paragraph5 =  new Paragraph("                                       Thank You, Please Visit Again.                               ");
            doc.add(paragraph5);
            
            
        }catch(Exception e){
            //Logger.getLogger(pdfGenerator.class.getName()).log(Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to print the bill?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            try{
                if(new File(path+""+id+".pdf").exists()){
                    Process p = Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler "+path+""+id+".pdf");
                }else{
                        System.out.println("File doesnt exist");
                        }
            }
                catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                        }
            }
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r=jTable1.getSelectedRow();
        String click = (jTable1.getModel().getValueAt(r, 0).toString());
        String sql = "SELECT * FROM checkin WHERE id='"+click+"'";
        try{
            ps=con.prepareCall(sql);
            rs=ps.executeQuery();
            if(rs.next()){
                id = rs.getInt(1);
                
                jTextField1.setText(rs.getString(10));
                jTextField2.setText(rs.getString(2));
                jTextField5.setText(rs.getString(3));
                jTextField9.setText(rs.getString(6));
                jTextField3.setText(rs.getString(9));
                jTextField6.setText(rs.getString(13));
                //jTextField4.setText(checkout);
                
                SimpleDateFormat myFormat = new SimpleDateFormat("dd/MM/yyyy");
                Calendar cal = Calendar.getInstance();
                jTextField4.setText(myFormat.format(cal.getTime()));
                
                String dateBeforeString = rs.getString(9);
                java.util.Date dateBefore = myFormat.parse(dateBeforeString);
                String dateAfterString = myFormat.format(cal.getTime());
                java.util.Date dateAfter = myFormat.parse(dateAfterString);
                long difference = dateAfter.getTime() - dateBefore.getTime();
                int daysstayed = (int)(difference/(1000*60*60*24));
                if(daysstayed==0){
                    daysstayed = 1;
                    jTextField7.setText(String.valueOf(daysstayed));
                    float price = Float.parseFloat(jTextField6.getText());
                    jTextField8.setText(String.valueOf(daysstayed*price));
                    jTextField9.setText(rs.getString(6));
                    roomType = rs.getString(12);
                    bedType = rs.getString(11);
                }else{
                    jTextField7.setText(String.valueOf(daysstayed));
                    float price = Float.parseFloat(jTextField6.getText());
                    jTextField8.setText(String.valueOf(daysstayed*price));
                    jTextField9.setText(rs.getString(6));
                    roomType = rs.getString(12);
                    bedType = rs.getString(11);  
                }    
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ReceptionistJFrame().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
