/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import database.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author nikhithajarabana
 */
public class CustomerRoomBookingJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRoomBookingJFrame
     */
        Connection con;
    ResultSet rs;
    Statement st;
    PreparedStatement ps;
    
    public CustomerRoomBookingJFrame() {
        initComponents();
        con = ConnectionProvider.getCon();
        
        CustomerNametxt.setEditable(false);
        Emailtxt.setEditable(false);
        
    }
    
    void getInfo(String username, String name){
     CustomerNametxt.setText(name);
     Emailtxt.setText(username);
    }
    
    String email;
    String bedtype;
    String roomtype;
    String roomno;
    String price;   
    String date;
    
    
    
    public void roomDetails(){
        jComboBox2.removeAllItems();
        Pricetxt.setText("");
        DateTxt.setText("");
        bedtype = (String)BedBox.getSelectedItem();
        roomtype=(String)TypeBox.getSelectedItem();
        
        
        try{
            //ResultSet rs=Select.getData("SELECT * FROM rooms WHERE bedtype='"+bedtype+"' AND roomtype='"+roomtype+"' AND status='Not Booked'");
            //String sql = "SELECT * FROM rooms WHERE bedtype='"+bedtype+"' AND roomtype='"+roomtype+"' AND status='Not Booked'";
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM rooms WHERE bedtype='"+bedtype+"' AND roomtype='"+roomtype+"' AND status='Not Booked'");
            while(rs.next())
            {
                jComboBox2.addItem(rs.getString(1));
                //jComboBox2.addItem(rs.getString(2));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CustomerNameLbl = new javax.swing.JLabel();
        CustomerNametxt = new javax.swing.JTextField();
        PhLbl = new javax.swing.JLabel();
        Phtxt = new javax.swing.JTextField();
        GenderLbl = new javax.swing.JLabel();
        GenderBox = new javax.swing.JComboBox<>();
        EmailLbl = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JTextField();
        NationalityLbl = new javax.swing.JLabel();
        Nationalitytxt = new javax.swing.JTextField();
        IDproofLbl = new javax.swing.JLabel();
        IDProoftxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Addresstxt = new javax.swing.JTextField();
        CheckInLbl = new javax.swing.JLabel();
        BedLbl = new javax.swing.JLabel();
        BedBox = new javax.swing.JComboBox<>();
        RoomTypeLbl = new javax.swing.JLabel();
        TypeBox = new javax.swing.JComboBox<>();
        RoomNoLbl = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Bookbtn = new javax.swing.JButton();
        Pricetxt = new javax.swing.JTextField();
        PriceLbl = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblMN = new javax.swing.JLabel();
        lblNation = new javax.swing.JLabel();
        DateTxt = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        PriceLbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Your Rooms!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 240, 40));

        CustomerNameLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        CustomerNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomerNameLbl.setText("Name");
        CustomerNameLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CustomerNameLblKeyReleased(evt);
            }
        });
        getContentPane().add(CustomerNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 124, 23));

        CustomerNametxt.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        CustomerNametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(CustomerNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 94, 280, 30));

        PhLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        PhLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PhLbl.setText("Mobile Number");
        getContentPane().add(PhLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 200, 25));

        Phtxt.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        Phtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Phtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PhtxtKeyReleased(evt);
            }
        });
        getContentPane().add(Phtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 94, 200, 30));

        GenderLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        GenderLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GenderLbl.setText("Gender");
        getContentPane().add(GenderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 124, 25));

        GenderBox.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        GenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        GenderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderBoxActionPerformed(evt);
            }
        });
        getContentPane().add(GenderBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 144, 121, 30));

        EmailLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        EmailLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLbl.setText("Email");
        getContentPane().add(EmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 124, 26));

        Emailtxt.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        Emailtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 270, 30));

        NationalityLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        NationalityLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NationalityLbl.setText("Nationality");
        getContentPane().add(NationalityLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 124, 23));

        Nationalitytxt.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        Nationalitytxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nationalitytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NationalitytxtKeyReleased(evt);
            }
        });
        getContentPane().add(Nationalitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 194, 280, 30));

        IDproofLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        IDproofLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IDproofLbl.setText("ID Proof");
        getContentPane().add(IDproofLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 124, 23));

        IDProoftxt.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        IDProoftxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(IDProoftxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 270, 30));

        jLabel2.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 124, 25));

        Addresstxt.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        Addresstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 244, 280, 30));

        CheckInLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        CheckInLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CheckInLbl.setText("Check In Date");
        getContentPane().add(CheckInLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 25));

        BedLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        BedLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BedLbl.setText("Bed Type");
        getContentPane().add(BedLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 92, 23));

        BedBox.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        BedBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bed Type", "Twin", "Queen", "King" }));
        BedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedBoxActionPerformed(evt);
            }
        });
        getContentPane().add(BedBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 150, 30));

        RoomTypeLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        RoomTypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RoomTypeLbl.setText("Room Type");
        getContentPane().add(RoomTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 110, 25));

        TypeBox.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        TypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Type", "AC", "Non-AC", " " }));
        TypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeBoxActionPerformed(evt);
            }
        });
        getContentPane().add(TypeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 160, 30));

        RoomNoLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        RoomNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RoomNoLbl.setText("Room No");
        getContentPane().add(RoomNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 92, 20));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 120, 30));

        Bookbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Bookbtn.setText("Book");
        Bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Bookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 110, 40));

        Pricetxt.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        getContentPane().add(Pricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 120, 30));

        PriceLbl.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        PriceLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PriceLbl.setText("Price");
        getContentPane().add(PriceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 92, -1));

        Backbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 160, 20));
        getContentPane().add(lblMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 200, 20));
        getContentPane().add(lblNation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 280, 20));
        getContentPane().add(DateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 150, 30));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 120, 30));

        PriceLbl1.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        PriceLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PriceLbl1.setText("Occupancy");
        getContentPane().add(PriceLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 92, -1));

        jLabel3.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CheckIn.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerNameLblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomerNameLblKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameLblKeyReleased

    private void PhtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhtxtKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{10,10}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Phtxt.getText());
        if(!match.matches()){
            lblMN.setText("Phone Number is not valid");
        }
        else{
            lblMN.setText("");
        }
    }//GEN-LAST:event_PhtxtKeyReleased

    private void GenderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderBoxActionPerformed

    private void NationalitytxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NationalitytxtKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z]{4,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Nationalitytxt.getText());
        if(!match.matches()){
            lblNation.setText("Nationality is incorrect");
        }
        else{
            lblNation.setText("");
        }
    }//GEN-LAST:event_NationalitytxtKeyReleased

    private void BedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedBoxActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_BedBoxActionPerformed

    private void TypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeBoxActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_TypeBoxActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        roomno=(String)jComboBox2.getSelectedItem();
        try{
            //ResultSet rs=Select.getData("SELECT * FROM rooms WHERE bedtype='"+bedtype+"' AND roomtype='"+roomtype+"' AND status='Not Booked'");
            //String sql = "SELECT * FROM rooms WHERE roomno='"+roomno+"'";
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM rooms WHERE roomno='"+roomno+"'");
            while(rs.next()){
                Pricetxt.setText(rs.getString(5));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
            setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void BookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookbtnActionPerformed
        // TODO add your handling code here:
                int id=1;
        String name = CustomerNametxt.getText();
        String mobileno = Phtxt.getText();
        String nationality = Nationalitytxt.getText();
        String email = Emailtxt.getText();
        String address = Addresstxt.getText();
        String idproof = IDProoftxt.getText();
        String roomType = (String)TypeBox.getSelectedItem();
        String bedType = (String)BedBox.getSelectedItem();
        String roomNo = (String)jComboBox2.getSelectedItem();
        String gender = (String)GenderBox.getSelectedItem();
        String price = Pricetxt.getText();
        String checkIn = DateTxt.getText();
                
        if(name.equals("")|| nationality.equals("")|| email.equals("")||address.equals("")||idproof.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please fill all the details");
            CustomerNametxt.setText("");
            Phtxt.setText("");
            Nationalitytxt.setText("");
            Emailtxt.setText("");
            Addresstxt.setText("");
            IDProoftxt.setText("");
        }
        else
        {
          try{
              String query = "Select max(id) from checkin";
              ps=con.prepareStatement(query);
              rs = ps.executeQuery();
              while(rs.next())
              {
                  id=rs.getInt(1);
              }
              id=id+1;
              if(!price.equals("")){
                  query = "UPDATE rooms set status='Booked' WHERE roomno='"+roomNo+"'";
                  ps=con.prepareStatement(query);
                  ps.executeUpdate();
                  String sql = "INSERT INTO checkin (id,name,mobileno,nationality,gender,email,idproof,address,checkin,roomno,bedType,roomType,price) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
                  ps=con.prepareStatement(sql);
                  ps.setInt(1,id);
                  ps.setString(2, name);
                  ps.setString(3,mobileno);
                  ps.setString(4,nationality);
                  ps.setString(5, gender);
                  ps.setString(6,email);
                  ps.setString(7, idproof);
                  ps.setString(8, address);
                  ps.setString(9,checkIn);
                  ps.setString(10,roomNo);
                  ps.setString(11, bedType);
                  ps.setString(12, roomType);
                  ps.setString(13, price);
                  ps.execute();
                  
                  CustomerNametxt.setText("");
                  Phtxt.setText("");
                  Nationalitytxt.setText("");
                  Emailtxt.setText("");
                  Addresstxt.setText("");
                  IDProoftxt.setText("");
                  setVisible(false);
                  new CustomerCheckInJFrame().setVisible(true);
              }
             
              
          }catch(Exception e)
          {
              JOptionPane.showMessageDialog(null,e);
          }
        }
    }//GEN-LAST:event_BookbtnActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRoomBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRoomBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRoomBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRoomBookingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRoomBookingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addresstxt;
    private javax.swing.JButton Backbtn;
    private javax.swing.JComboBox<String> BedBox;
    private javax.swing.JLabel BedLbl;
    private javax.swing.JButton Bookbtn;
    private javax.swing.JLabel CheckInLbl;
    private javax.swing.JLabel CustomerNameLbl;
    private javax.swing.JTextField CustomerNametxt;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JTextField IDProoftxt;
    private javax.swing.JLabel IDproofLbl;
    private javax.swing.JLabel NationalityLbl;
    private javax.swing.JTextField Nationalitytxt;
    private javax.swing.JLabel PhLbl;
    private javax.swing.JTextField Phtxt;
    private javax.swing.JLabel PriceLbl;
    private javax.swing.JLabel PriceLbl1;
    private javax.swing.JTextField Pricetxt;
    private javax.swing.JLabel RoomNoLbl;
    private javax.swing.JLabel RoomTypeLbl;
    private javax.swing.JComboBox<String> TypeBox;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNation;
    // End of variables declaration//GEN-END:variables
}
