/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import database.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sahithi
 */
public class CustomerLogin extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    /**
     * Creates new form CustomerLogin
     */
    public CustomerLogin() {
        initComponents();
        con = ConnectionProvider.getCon();
    }
    
    /*void callfunc(){
        String query = "SELECT * FROM checkin WHERE roomno=?";    
                try{
                ps=con.prepareStatement(query);
                rs=ps.executeQuery();
                if(rs.next())
                {
                    String roomno=rs.getString(10);
                    //String occupancy=rs.getString(14);
                    this.dispose();
        CustomerServiceJFrame food = new CustomerServiceJFrame();
        food.setVisible(true);
        food.getInfo(roomno);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Incorrect Credentials");
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        CustomerLoginLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 118));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 190, 40));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 190, 40));

        CustomerLoginLbl.setFont(new java.awt.Font("Big Caslon", 1, 48)); // NOI18N
        CustomerLoginLbl.setText("Guest Login");
        getContentPane().add(CustomerLoginLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 270, -1));

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guest BAckground.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email = jTextField1.getText();
        String password = jPasswordField1.getText();
        if(email.equals("")|| password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter all fields");
        }
        else if(email.equals("staff")&& password.equals("staff") )
        {
            StaffLoginJFrame staffpanel = new StaffLoginJFrame();
            staffpanel.setVisible(true);
            this.dispose();
        }
        else
        {
            String roomno = jTextField1.getText();
            //ResultSet rs = select.getData("select * from members where username='"+email+"'and password='"+password+"'");
            try{
                String sql = "SELECT * FROM checkin WHERE roomno=? AND name=?";
                ps=con.prepareStatement(sql);
                ps.setString(1, jTextField1.getText());
                ps.setString(2,jPasswordField1.getText());
                //ps.setString(WIDTH, sql);
                rs=ps.executeQuery();
                
                if(rs.next())
                {
                    //callfunc();
                    /*check=1;
                    if(rs.getString(8).equals(true))
                    {
                    setVisible(false);
                    new ManagerLoginJFrame().setVisible(true);
                    }*/
                    //JOptionPane.showMessageDialog(null, "Login Successful");
                    roomno=rs.getString(10);
                    //String occupancy=rs.getString(14);
                    this.dispose();
                    CustomerServiceJFrame food = new CustomerServiceJFrame();
                    food.setVisible(true);
                    food.getInfo(roomno);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Incorrect Credentials");
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                }
                }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                }
        }     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomePage homepanel = new HomePage();
        homepanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerLoginLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
