/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author nikhithajarabana
 */
public class FoodServiceJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FoodServiceJFrame
     */
    public FoodServiceJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BFRbtn = new javax.swing.JRadioButton();
        LRbtn = new javax.swing.JRadioButton();
        DRbtn = new javax.swing.JRadioButton();
        DineInRbtn = new javax.swing.JRadioButton();
        RSBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        OrderTxt = new javax.swing.JTextField();
        Oderbtn = new javax.swing.JButton();
        RoomNoTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setText("Want Some Yummy Food ? Order Here !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Room No:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        buttonGroup1.add(BFRbtn);
        BFRbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        BFRbtn.setText("Breakfast");
        BFRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFRbtnActionPerformed(evt);
            }
        });
        getContentPane().add(BFRbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        buttonGroup1.add(LRbtn);
        LRbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        LRbtn.setText("Lunch");
        getContentPane().add(LRbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        buttonGroup1.add(DRbtn);
        DRbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        DRbtn.setText("Dinner");
        DRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRbtnActionPerformed(evt);
            }
        });
        getContentPane().add(DRbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        buttonGroup2.add(DineInRbtn);
        DineInRbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        DineInRbtn.setText("Dine-in");
        getContentPane().add(DineInRbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        buttonGroup2.add(RSBtn);
        RSBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        RSBtn.setText("Room Service");
        RSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RSBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Type :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Where would you like your food served?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Order :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("(You can find the menu in your room.)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("(Please enter the dishes along with quantity.)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, 20));

        OrderTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderTxtActionPerformed(evt);
            }
        });
        getContentPane().add(OrderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 310, -1));

        Oderbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Oderbtn.setText("Order ");
        Oderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OderbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Oderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));
        getContentPane().add(RoomNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FoodServide.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DRbtnActionPerformed

    private void BFRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFRbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BFRbtnActionPerformed

    private void RSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSBtnActionPerformed

    private void OrderTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderTxtActionPerformed

    private void OderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OderbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OderbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodServiceJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BFRbtn;
    private javax.swing.JRadioButton DRbtn;
    private javax.swing.JRadioButton DineInRbtn;
    private javax.swing.JRadioButton LRbtn;
    private javax.swing.JButton Oderbtn;
    private javax.swing.JTextField OrderTxt;
    private javax.swing.JRadioButton RSBtn;
    private javax.swing.JTextField RoomNoTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
