/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import database.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.Chef;

/**
 *
 * @author nikhithajarabana
 */
public class FoodServiceJFrame extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form FoodServiceJFrame
     */
    public FoodServiceJFrame() {
        initComponents();
        con = ConnectionProvider.getCon();
        
        RoomNoTxt.setEditable(false);
        PeopleTxt.setEditable(false);
    }
    
    void getInfo(String roomno,String occupancy){
     RoomNoTxt.setText(roomno);
     PeopleTxt.setText(occupancy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PeopleTxt = new javax.swing.JTextField();
        Oderbtn = new javax.swing.JButton();
        RoomNoTxt = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 118));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("AppleGothic", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Want Some Yummy Food ? Order Here !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room No:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Food Type :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 30));

        jLabel5.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Guest Count :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        PeopleTxt.setBackground(new java.awt.Color(0, 51, 51));
        PeopleTxt.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        PeopleTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PeopleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 190, 30));

        Oderbtn.setBackground(new java.awt.Color(0, 51, 51));
        Oderbtn.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        Oderbtn.setForeground(new java.awt.Color(255, 255, 255));
        Oderbtn.setText("Order ");
        Oderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OderbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Oderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        RoomNoTxt.setBackground(new java.awt.Color(0, 51, 51));
        RoomNoTxt.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        RoomNoTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(RoomNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 200, 30));

        jCheckBox1.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 51, 51));
        jCheckBox1.setText("Breakfast");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, 30));

        jCheckBox2.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 51, 51));
        jCheckBox2.setText("Lunch");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(0, 51, 51));
        jCheckBox3.setText("Dinner");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        BackButton.setBackground(new java.awt.Color(0, 51, 51));
        BackButton.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.setBorder(null);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        jLabel4.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Meal Type :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veg", "Non Veg" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FoodServide.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OderbtnActionPerformed
        // TODO add your handling code here:
        int roomno = Integer.parseInt(RoomNoTxt.getText());
        String mealtype = " ";
        if(jCheckBox1.isSelected()|| jCheckBox2.isSelected()||jCheckBox3.isSelected()){
            try{
                if(jCheckBox1.isSelected())
                {
                    mealtype = "Breakfast";
                }
                else if(jCheckBox2.isSelected()){
                    mealtype = "Lunch";
                }
                else if(jCheckBox3.isSelected()){
                    mealtype = "Dinner";
                }
                else if(jCheckBox1.isSelected() && jCheckBox2.isSelected()){
                    mealtype ="Breakfast,Lunch";
                }
                else if(jCheckBox1.isSelected() && jCheckBox3.isSelected()){
                mealtype ="Breakfast,Dinner";
                }
                else if(jCheckBox2.isSelected() && jCheckBox3.isSelected()){
                    mealtype ="Lunch,Dinner";
                }
                else{
                    mealtype ="Breakfast,Lunch,Dinner";
                } 
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select atleast one mealtype");
            
        }
        
        String NoOfPeople = PeopleTxt.getText();
        
        if(RoomNoTxt.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter room number");
        }
        else{
        Connection con = ConnectionProvider.getCon();
        Chef c = new Chef();
        c.setRoomno(roomno);
        c.setMealtype(mealtype);
        c.setNoOfPeople(NoOfPeople);
        
        //c.setStatus(status);
        try{
                String sql = "INSERT INTO chef(roomno,mealtype,location,special_instructions) VALUES (?,?,?,?)";
                ps=con.prepareStatement(sql);
                ps.setInt(1,roomno);
                ps.setString(2, mealtype);
                ps.setString(3, NoOfPeople);
                
                ps.execute();
                
                RoomNoTxt.setText("");
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(false);
                
                PeopleTxt.setText("");
                
                con.close();
                
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_OderbtnActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerServiceJFrame().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodServiceJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Oderbtn;
    private javax.swing.JTextField PeopleTxt;
    private javax.swing.JTextField RoomNoTxt;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
