/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import java.sql.*;
import database.ConnectionProvider;

/**
 *
 * @author sahithi
 */
public class ForgotPasswordJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordJFrame
     */
    public ForgotPasswordJFrame() {
        initComponents();
    }
    String email;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sqcombobox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel2.setText("Oops ! Forgot Password ?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel3.setText("Email :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 80, 30));

        Emailtxt.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Emailtxt.setForeground(new java.awt.Color(255, 204, 102));
        getContentPane().add(Emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 230, 30));

        searchbtn.setBackground(new java.awt.Color(0, 0, 0));
        searchbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 51));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel4.setText("Security Question : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        sqcombobox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sqcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What's your first pets name?", "What's your favourite city?", "What's your mothers maidens name?", "What's your native place?" }));
        getContentPane().add(sqcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 232, 230, 30));

        jLabel6.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel6.setText("Answer :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 277, 230, 30));

        jLabel5.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel5.setText("New Password :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 150, -1));

        savebtn.setBackground(new java.awt.Color(153, 153, 153));
        savebtn.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, -1));

        jLabel1.setFont(new java.awt.Font("Apple Chancery", 1, 48)); // NOI18N
        jLabel1.setText("Palm Tree Resorts");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        homeButton.setBackground(new java.awt.Color(0, 0, 0));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2022-11-30 at 8.57.36 PM.jpeg"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 80, 60));

        loginbtn.setBackground(new java.awt.Color(153, 153, 153));
        loginbtn.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 90, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 6, -1, -1));

        ExitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 34, -1, 34));

        jPasswordField1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 230, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whitebg.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        HomePage homepanel = new HomePage();
        homepanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        LoginJFrame loginpanel = new LoginJFrame();
        loginpanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        int check=0;
        email=Emailtxt.getText();
        if(email.equals(""))
        {
            check=1;
            JOptionPane.showMessageDialog(null, "Please enter email");
        }
        else{
            ResultSet rs =Select.getData("Select *from users where email='"+email+"'");
            try
            {
                if(rs.next())
                {
                    check=1;
                    sqcombobox.setEditable(false);
                    Emailtxt.setEditable(false);
                    sqcombobox.setEditable(false);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(check==0)
            JOptionPane.showMessageDialog(null,"Email doesnot exists");
    }//GEN-LAST:event_searchbtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDailog(null,"Do you really want to close the application");
        if(a==0)
            System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        int check=0;
        String securityQuestion=sqcombobox.getActionCommand();
        String answer=jTextField1.getText();
        String newPassword=jPasswordField1.getText();
        if(answer.equals("") || newPassword equals(""))
        {
            check=1;
            JOptionPane.showMessageDialog(null,"All Field are Required");
        }
        else
        {
                Resultset rs=Select.getData("Select from where email= '"+email+"' and securityQuestion='"+securityQuestion+"' and answer='"+answer+"'");
                try
                {
                    if(rs.next())
                    {
                        check=1;
                        InsertUpdateDelete.setData("Update users set password='"+newPassword+"' where email ='"+email+"'","Password Set Successfull");
                        setVisible(false);
                        new ForgotPassword().setVisible(true);
                    }
                }
                catch(Exception e)
                {
                JOptionPane.showMessageDialog(null,e);
                }
        }
        if(check==0)
            JOptionPane.showMessageDialog(null,"Incorrect Answer");
    }//GEN-LAST:event_savebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JComboBox<String> sqcombobox;
    // End of variables declaration//GEN-END:variables
}
