/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author nikhithajarabana
 */
public class ManagerLoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerLoginJFrame
     */
    public ManagerLoginJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EmpDirbtn = new javax.swing.JButton();
        Roomsbtn = new javax.swing.JButton();
        Bookingsbtn = new javax.swing.JButton();
        Clockinbtn = new javax.swing.JButton();
        ClockOutBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Hello Manager !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        EmpDirbtn.setBackground(new java.awt.Color(255, 255, 204));
        EmpDirbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        EmpDirbtn.setText("Employee Directory ");
        getContentPane().add(EmpDirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        Roomsbtn.setBackground(new java.awt.Color(255, 255, 204));
        Roomsbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Roomsbtn.setText("List of Rooms");
        getContentPane().add(Roomsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 290, 150, -1));

        Bookingsbtn.setBackground(new java.awt.Color(255, 255, 204));
        Bookingsbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Bookingsbtn.setText("Bookings ");
        getContentPane().add(Bookingsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 350, 140, -1));

        Clockinbtn.setBackground(new java.awt.Color(255, 255, 204));
        Clockinbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Clockinbtn.setText("Clock in");
        Clockinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockinbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Clockinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 120, -1));

        ClockOutBtn.setBackground(new java.awt.Color(255, 255, 204));
        ClockOutBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ClockOutBtn.setText("Clock Out ");
        getContentPane().add(ClockOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 120, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hotel Manager.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClockinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockinbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClockinbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerLoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookingsbtn;
    private javax.swing.JButton ClockOutBtn;
    private javax.swing.JButton Clockinbtn;
    private javax.swing.JButton EmpDirbtn;
    private javax.swing.JButton Roomsbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
