/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import database.ConnectionProvider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author nikhithajarabana
 */
public class ViewCustomerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewCustomerJFrame
     */
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public ViewCustomerJFrame() {
        initComponents();
        con = ConnectionProvider.getCon();
        populateTable();
    }
    
    public void populateTable()
    {
        try{
            String sql = "SELECT * FROM customerlogin";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            CustomersTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CustomersTable = new javax.swing.JTable();
        SearchTxt = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 118));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomersTable.setBackground(new java.awt.Color(204, 204, 204));
        CustomersTable.setFont(new java.awt.Font("Big Caslon", 1, 18)); // NOI18N
        CustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Email", "Security Question", "Answer"
            }
        ));
        CustomersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomersTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 970, 340));
        getContentPane().add(SearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 30));

        Searchbtn.setFont(new java.awt.Font("Big Caslon", 1, 18)); // NOI18N
        Searchbtn.setText("Search");
        Searchbtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchbtnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchbtnFocusLost(evt);
            }
        });
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });
        Searchbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchbtnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchbtnKeyReleased(evt);
            }
        });
        getContentPane().add(Searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        Backbtn.setFont(new java.awt.Font("Big Caslon", 1, 18)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        jButton1.setFont(new java.awt.Font("Big Caslon", 1, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 90, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setFont(new java.awt.Font("Big Caslon", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Member  Details");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersTableMouseClicked
        // TODO add your handling code here:
        int r=CustomersTable.getSelectedRow();
        String click = (CustomersTable.getModel().getValueAt(r, 0).toString());
        String sql = "SELECT * FROM customerlogin WHERE firstname='"+click+"'";
        try{
            ps=con.prepareCall(sql);
            rs=ps.executeQuery();
            if(rs.next()){
                String firstname = rs.getString(1);
                String lastname = rs.getString(2);
                String email = rs.getString(3);
                String securityques = rs.getString(4);
                String answer = rs.getString(5);
            }  
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }     
    }//GEN-LAST:event_CustomersTableMouseClicked

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        new AdminJframe().setVisible(true);
        AdminJframe adminpanel = new AdminJframe();
        adminpanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void SearchbtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchbtnFocusGained
        // TODO add your handling code here:
                if(SearchTxt.getText().equals("Search...."))
        {
            SearchTxt.setText("");
            SearchTxt.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_SearchbtnFocusGained

    private void SearchbtnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchbtnFocusLost
        // TODO add your handling code here:
               if(SearchTxt.getText().equals(""))
        {
            SearchTxt.setText("Search....");
            SearchTxt.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_SearchbtnFocusLost

    private void SearchbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchbtnKeyPressed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) CustomersTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        CustomersTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(SearchTxt.getText().trim()));
    }//GEN-LAST:event_SearchbtnKeyPressed

    private void SearchbtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchbtnKeyReleased
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) CustomersTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        CustomersTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(SearchTxt.getText().trim()));
    }//GEN-LAST:event_SearchbtnKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r=CustomersTable.getSelectedRow();
        String click = (CustomersTable.getModel().getValueAt(r, 0).toString());
        String sql = "DELETE FROM customerlogin WHERE firstname='"+click+"'";
        try{
            if(CustomersTable.getSelectedRowCount()==1){
                ps=con.prepareCall(sql);
                int i = JOptionPane.showConfirmDialog(null, "Are you sure, you want to delete?","Deletion",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(i==JOptionPane.YES_OPTION){
                ps.execute();
                JOptionPane.showMessageDialog(null,"Deleted Successfully.");
                new ViewCustomerJFrame().setVisible(true);
                }   
            }
            else if(CustomersTable.getSelectedRowCount()==0){
                    JOptionPane.showMessageDialog(null, "Please select a row to delete");
                }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbtnActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCustomerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTable CustomersTable;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
